language: python
python:
  - "3.6"
env:
  PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/tests:$TRAVIS_BUILD_DIR/sanic_boilerplate
install:
  pip install -r requirements.txt
script:
  - py.test --cov=my_app tests/
after_success:
  - coveralls